sudo: false

language: node_js

node_js:
  - '16'

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm install -g @angular/cli

script:
  # - ng lint
  - ng build
